# SHIM de compatibilité (refactor — phase migration).
#
# L'état activité (statuts, TypedDicts, helpers) a déménagé vers
# app/schemas/activity.py. SUPPRESSION prévue phase cleanup (§30).
from app.schemas.activity import (
    ACTIVITY_ABANDONED,
    ACTIVITY_CHECKING_UNDERSTANDING,
    ACTIVITY_COMPLETED,
    ACTIVITY_EVALUATING,
    ACTIVITY_GIVING_HINT,
    ACTIVITY_IDLE,
    ACTIVITY_TYPE_EXERCISE,
    ACTIVITY_TYPE_QUIZ,
    ACTIVITY_TYPE_UNDERSTANDING_CHECK,
    ACTIVITY_WAITING_ANSWER,
    ACTIVITY_WAITING_RETRY,
    ALL_ACTIVITY_STATUSES,
    ALL_RESPONSE_TYPES,
    RESPONSE_TYPE_CODE,
    RESPONSE_TYPE_MULTIPLE_CHOICE,
    RESPONSE_TYPE_SHORT_ANSWER,
    RESPONSE_TYPE_TEXT,
    RESPONSE_TYPE_TRUE_FALSE,
    ActivityLogEntry,
    LearningActivityState,
    QuizState,
    new_activity_id,
    summarize_activity,
)

__all__ = [
    "ACTIVITY_IDLE",
    "ACTIVITY_WAITING_ANSWER",
    "ACTIVITY_EVALUATING",
    "ACTIVITY_GIVING_HINT",
    "ACTIVITY_WAITING_RETRY",
    "ACTIVITY_CHECKING_UNDERSTANDING",
    "ACTIVITY_COMPLETED",
    "ACTIVITY_ABANDONED",
    "ALL_ACTIVITY_STATUSES",
    "ACTIVITY_TYPE_EXERCISE",
    "ACTIVITY_TYPE_QUIZ",
    "ACTIVITY_TYPE_UNDERSTANDING_CHECK",
    "RESPONSE_TYPE_TEXT",
    "RESPONSE_TYPE_CODE",
    "RESPONSE_TYPE_MULTIPLE_CHOICE",
    "RESPONSE_TYPE_SHORT_ANSWER",
    "RESPONSE_TYPE_TRUE_FALSE",
    "ALL_RESPONSE_TYPES",
    "LearningActivityState",
    "QuizState",
    "ActivityLogEntry",
    "new_activity_id",
    "summarize_activity",
]
